stages:
  - build
  - dockerize

variables:
  DOCKER_IMAGE: my-flask-app:latest

build:
  stage: build
  script:
    - echo "Building the app"
    

dockerize:
  stage: dockerize
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main  

